name: XmPrep
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^1.0.2
  image_picker_platform_interface: ^1.1.0
  nice_button: ^0.1.7
  image_picker: ^0.6.0+9
  pin_entry_text_field: ^0.1.4
  font_awesome_flutter: ^8.2.0
  flutter_svg: ^0.18.0
  flutter_staggered_grid_view: "^0.3.2"
  bottom_navy_bar: ^5.5.0
  bubble_bottom_bar: ^1.2.0
  commons: ^0.7.8+3
  lite_rolling_switch: ^0.1.1
    # if you are using latest flutter please update your flutter_svg package to ^0.18.*
  # help us to use SVG in our app
  provider: ^4.3.1 # for State management

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  intl: ^0.16.1
  animations: ^1.0.0+5
  rich_alert: ^0.1.32
  webview_flutter: ^0.3.18+1
  tuple: ^1.0.3
  english_words: ^3.1.3
  # Check that you have this dependency (added in the previous step)
  firebase_core: ^0.3.0
  firebase_auth:
  cloud_firestore:
  flutter_form_builder:
  firebase_storage:
  firebase_database:
  toast: ^0.1.5
  dependencies:
  modal_progress_hud: ^0.1.3
  geolocator:
  device_info:












dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^0.18.0
  google_fonts: ^1.0.0
  flutter_swiper: ^1.1.6
  flutter_super_state: ^0.2.0
  carousel_slider: ^2.2.1
  sliding_card: ^0.1.2
  fluttertoast: ^7.1.1



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/icons/
    - images/LOGO.png
    - images/1.jpg
    - images/2.jpg
    - images/3.jpg
    - images/pngfuel.com.png
    - images/s1-removebg-preview.png
    - images/s2-removebg-preview.png
    - images/s3-removebg-preview.png
    - images/C-programming.png
    - images/python-programming.jpg
    - images/ic_avatar.png
    - images/ic_camera.png
    - images/sir.jpg
    - images/students.jpg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
